# Generated by Django 4.2.2 on 2023-06-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ques1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAT', models.IntegerField(null=True)),
                ('Random', models.IntegerField(null=True)),
                ('GPA', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ques2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
            ],
        ),
    ]
