# Generated by Django 4.2.2 on 2023-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0002_ques3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('email', models.CharField(max_length=1000)),
                ('bio', models.CharField(max_length=1000)),
                ('age', models.CharField(max_length=1000)),
            ],
        ),
    ]
