# Generated by Django 4.2.2 on 2023-07-04 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='StudentData',
        ),
    ]
