# Generated by Django 4.2.2 on 2023-07-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0006_datascraped_delete_studentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascraped',
            name='Academic',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
