# Generated by Django 4.2.2 on 2023-07-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0007_alter_datascraped_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascraped',
            name='Academic',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
