# Generated by Django 4.2.2 on 2023-07-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0009_alter_datascraped_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datascraped',
            name='Academic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
