# Generated by Django 4.2.2 on 2023-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0012_data_delete_josaadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
