# Generated by Django 4.2.2 on 2023-07-06 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josaa_portal', '0014_datareq_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ques1',
        ),
        migrations.DeleteModel(
            name='Ques2',
        ),
        migrations.DeleteModel(
            name='Ques3',
        ),
        migrations.DeleteModel(
            name='Ques4',
        ),
    ]
